/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ThinkPhpPlugin.Files;

import ThinkPhpPlugin.Entrance;
import ThinkPhpPlugin.ThinkphpCreateProject;
import ThinkPhpPlugin.ThinkphpFile;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.WizardDescriptor;

public final class FileModelVisualPanel1 extends JPanel implements DocumentListener{

    //private Project project;
    public static final String PROP_Model_NAME = "Empty";
    String p_name="";
    String p_path="";
    private FileModelWizardPanel1 panel;
    /** Creates new form FileModelVisualPanel1 */
    public FileModelVisualPanel1(FileModelWizardPanel1 panel) {
        initComponents();
        this.panel = panel;
        ThinkphpCreateProject CreateProject=new ThinkphpCreateProject();
        //this.project=OpenProjects.getDefault().getOpenProjects()[0];
        p_name=CreateProject.GetProjectName();
        p_path=CreateProject.GetProjectDir();
        project_name.setText(p_name);
        create_file.setText(p_path+"/Lib/Action/"+PROP_Model_NAME+"Model.class.php");
        model_name.getDocument().addDocumentListener(this);

        Entrance en=new Entrance();
        ArrayList<String> list=en.GetEntrance();
        for(int i=0;i<list.size();i++)
        {
            entrance_folds.addItem(list.get(i));
        }
    }

    @Override
    public String getName() {
        return "名称和位置";
    }

    @Override
    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
        model_name.requestFocus();
    }

    void read(WizardDescriptor wizardDescriptor) {
        //throw new UnsupportedOperationException("Not yet implemented");
    }

    void store(WizardDescriptor d) {
        String model_name_str=model_name.getText().trim();
        String entrance_fold=(String) entrance_folds.getSelectedItem();
        String file_name = p_path+File.separatorChar+entrance_fold+File.separatorChar+"Lib"+File.separatorChar+"Model"+File.separatorChar+model_name_str+"Model.class.php";
        d.putProperty("file_name", file_name);
        d.putProperty("entrance_fold", entrance_fold);
        d.putProperty("model_name", model_name_str);
    }

    boolean valid(WizardDescriptor wizardDescriptor) {
        if(model_name.getText().length()==0)
        {
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "模型名称不能为空。");
            return false;
        }

        if (ThinkphpFile.ExistFile(create_file.getText())) {
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "模型名称已经存在。");
            return false;
        }
        wizardDescriptor.putProperty("WizardPanel_errorMessage","");
        return true;
    }

    void validate(WizardDescriptor wizardDescriptor) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        model_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        project_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        create_file = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entrance_folds = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(541, 135));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.jLabel1.text")); // NOI18N

        model_name.setText(org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.model_name.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.jLabel3.text")); // NOI18N

        project_name.setText(org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.project_name.text")); // NOI18N
        project_name.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.jLabel4.text")); // NOI18N

        create_file.setText(org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.create_file.text")); // NOI18N
        create_file.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(FileModelVisualPanel1.class, "FileModelVisualPanel1.jLabel5.text")); // NOI18N

        entrance_folds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrance_foldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model_name, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entrance_folds, 0, 445, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(project_name, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(create_file, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrance_folds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(project_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entrance_foldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrance_foldsActionPerformed
        // TODO add your handling code here:
        String action_name=model_name.getText();
        String entrance_fold=(String) entrance_folds.getSelectedItem();
        String file_name = p_path+File.separatorChar+entrance_fold+File.separatorChar+"Lib"+File.separatorChar+"Model"+File.separatorChar+action_name+"Model.class.php";
        create_file.setText(file_name);
}//GEN-LAST:event_entrance_foldsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField create_file;
    private javax.swing.JComboBox entrance_folds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField model_name;
    private javax.swing.JTextField project_name;
    // End of variables declaration//GEN-END:variables

    public void changedUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    public void insertUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    public void removeUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    /** Handles changes in the Project name and project directory, */
    private void updateTexts(DocumentEvent e) {
        String action_name=model_name.getText();
        String entrance_fold=(String) entrance_folds.getSelectedItem();
        String file_name = p_path+File.separatorChar+entrance_fold+File.separatorChar+"Lib"+File.separatorChar+"Model"+File.separatorChar+action_name+"Model.class.php";
        create_file.setText(file_name);
        panel.fireChangeEvent();
        
        /*String model_name_str=model_name.getText();
        String file_name = p_path+File.separatorChar+"Lib"+File.separatorChar+"Model"+File.separatorChar+model_name_str+"Model.class.php";
        create_file.setText(file_name);
        panel.fireChangeEvent(); // Notify that the panel changed*/
    }
}

